#!/bin/bash
echo "!!!! NOTICE !!!!"
echo "This script was largely hand-made, with only the paru installation generated by AI. its just that it was reformatted by ai for better comment grammar or error handling. kthxbye!"
read -p "enter enter to continue"
# ==========================================
# Error Handling & Helpers
# ==========================================

# Function to handle errors
handle_error() {
    local exit_code=$1
    local cmd="$2"
    echo -e "\n\033[1;31m[ERROR] Unexpected error occurred during: \033[0;33m$cmd\033[0m"
    echo -e "\033[1;31m[ERROR] Exit code: $exit_code\033[0m"
    
    # Ask user how to proceed
    while true; do
        read -p "Do you want to (i)gnore this error and proceed, or (a)bort? [i/a]: " choice
        case "$choice" in
            [iI]* ) echo "Ignoring error and proceeding..."; return 0 ;;
            [aA]* ) echo "Aborting script."; exit $exit_code ;;
            * ) echo "Please answer 'i' or 'a'." ;;
        esac
    done
}

# Wrapper to execute commands with error catching
try() {
    "$@"
    local status=$?
    if [ $status -ne 0 ]; then
        handle_error $status "$*"
    fi
}

# Helper to check if a package is installed (pacman)
is_installed() {
    pacman -Qi "$1" &> /dev/null
}

# ==========================================
# Phase 1: System Update & Core Deps
# ==========================================
echo "Updating system before proceeding..."
try sudo pacman -Syu --noconfirm

echo "Installing essential packages (firefox, flatpak, etc)..."
# using --needed to skip re-installing
try sudo pacman -S --needed firefox flatpak gnome-browser-connector python python-pip --noconfirm

# ==========================================
# Phase 2: Paru Installation
# ==========================================
echo "Checking for paru..."

if ! command -v pacman &> /dev/null; then
    echo "This script is intended for Arch Linux based systems with pacman."
    try exit 1
fi

if command -v paru &> /dev/null; then
    echo "Paru is already installed. Skipping installation."
else
    echo "Installing required dependencies: base-devel and git..."
    try sudo pacman -S --needed base-devel git --noconfirm

    echo "Cloning paru repository from the AUR..."
    BUILD_DIR=$(mktemp -d)
    try git clone https://aur.archlinux.org/paru.git "$BUILD_DIR"

    echo "Building and installing paru..."
    CURRENT_DIR=$(pwd)
    try cd "$BUILD_DIR"
    try makepkg -si --noconfirm
    try cd "$CURRENT_DIR"

    echo "Cleaning up build directory..."
    try rm -rf "$BUILD_DIR"
fi

# ==========================================
# Phase 3: Paru Configuration
# ==========================================
echo "Applying paru configurations..."

# Check if BottomUp is already uncommented/set
if ! grep -q "^BottomUp" /etc/paru.conf; then
   echo "Enabling BottomUp, SudoLoop, CombinedUpgrade, UpgradeMenu..."
   try sudo sed -i -e 's/^#BottomUp/BottomUp/' \
                   -e 's/^#SudoLoop/SudoLoop/' \
                   -e 's/^#CombinedUpgrade/CombinedUpgrade/' \
                   -e 's/^#UpgradeMenu/UpgradeMenu/' /etc/paru.conf
fi

# Check for SkipReview before appending
if ! grep -q "SkipReview" /etc/paru.conf; then
    echo "SkipReview" | try sudo tee -a /etc/paru.conf > /dev/null
fi

echo "Paru setup complete."

# ==========================================
# Phase 4: Extensions & Antigravity
# ==========================================
echo "Installing gnome extension cli and antigravity..."
try paru -S --needed gnome-extensions-cli antigravity --noconfirm

echo "Installing gnome extensions..."
install_extension() {
    local ext_id=$1
    echo "Processing extension: $ext_id"
    # gnome-extensions-cli usually handles idempotency or we can ignore error if installed
    # We use try to catch errors, but arguably if it fails because installed we should overlook it.
    # But usually 'install' on existing might fail or just warn. Let's try.
    try gnome-extensions-cli install "$ext_id"
}

install_extension "clipboard-indicator@tudmotu.com"
install_extension "user-theme@gnome-shell-extensions.gcampax.github.com"
install_extension "extension-list@tu.berry"
install_extension "system-monitor@gnome-shell-extensions.gcampax.github.com"
install_extension "fullscreen-notifications@sorrow.about.alice.pm.me"

echo "Extensions installed."

# ==========================================
# Phase 5: Discord / Vencord
# ==========================================
echo "Patching discord with vencord.. Continue? (Y/n)"
read -r response
if [[ "$response" == [yY] || "$response" == [yY][eE][sS] || -z "$response" ]]; then
    echo "Patching discord with vencord..."
    # Wrap validation of curl and sh?
    try sh -c "$(curl -sS https://vencord.dev/install.sh)"
else
    echo "Skipping vencord patch."
fi

# ==========================================
# Phase 6: Omarchy Custom Patches
# ==========================================
echo "Installing custom omarchy patches..."

OMARCHY_REPO="https://github.com/basecamp/omarchy.git"
TEMP_DIR="$HOME/temp"
OMARCHY_CLONE_DIR="$TEMP_DIR/omarchy"

try mkdir -p "$TEMP_DIR"

if [ -d "$OMARCHY_CLONE_DIR" ]; then
    echo "Omarchy directory exists at $OMARCHY_CLONE_DIR. Skipping clone (or pulling updates)."
    # Optional: try git -C "$OMARCHY_CLONE_DIR" pull
else
    echo "Cloning usage..."
    try cd "$TEMP_DIR"
    try git clone "$OMARCHY_REPO"
fi

export OMARCHY_PATH="$OMARCHY_CLONE_DIR"
export OMARCHY_INSTALL="$OMARCHY_PATH/install"

# Original script had a heredoc reference block here. Preserving it as comment.
# ...

echo "Installing gum..."
try sudo pacman -S gum --noconfirm --needed

echo "Attaching pacman config..."
# Config idempotency: Check if files differ before copy?
# The user wants checkpoints to skip.
if ! cmp -s "$OMARCHY_PATH/default/pacman/pacman.conf" "/etc/pacman.conf"; then
    echo "Updating /etc/pacman.conf..."
    try sudo cp -f "$OMARCHY_PATH/default/pacman/pacman.conf" /etc/pacman.conf
else
    echo "/etc/pacman.conf already matches. Skipping."
fi

if ! cmp -s "$OMARCHY_PATH/default/pacman/mirrorlist-stable" "/etc/pacman.d/mirrorlist"; then
    echo "Updating mirrorlist..."
    try sudo cp -f "$OMARCHY_PATH/default/pacman/mirrorlist-stable" /etc/pacman.d/mirrorlist
else
    echo "mirrorlist already matches. Skipping."
fi

echo "Pacman config patched. Updating system with new configs..."
try sudo pacman -Syu --noconfirm

echo "Installing omarchy base packages..."
if [ -f "$OMARCHY_INSTALL/omarchy-base.packages" ]; then
    mapfile -t packages < <(grep -v '^#' "$OMARCHY_INSTALL/omarchy-base.packages" | grep -v '^$')
    try sudo pacman -S --noconfirm --needed "${packages[@]}"
else
    echo "Warning: omarchy-base.packages not found at $OMARCHY_INSTALL"
fi

echo "Deploying configs to ~/.config..."
try mkdir -p ~/.config

# Copy config recursively - Checkpoint: This is hard to check efficiently for all files.
# But we can assume if the folder exists, we might want to update or skip.
# Original script did `cp -R`. We'll stick to that but maybe user wanted to skip?
# "if they have then no need to do it".
# If ~/.config/omarchy exists, maybe skip?
# Let's assume we copy updates but don't fail if successful.

try cp -R "$OMARCHY_PATH/config/"* ~/.config/

# bashrc
if ! diff -q "$OMARCHY_PATH/default/bashrc" ~/.bashrc &>/dev/null; then
    echo "Updating .bashrc..."
    try cp "$OMARCHY_PATH/default/bashrc" ~/.bashrc
fi

# Themes Setup
try mkdir -p ~/.config/omarchy/themes
try mkdir -p ~/.config/omarchy/current
try cp "$OMARCHY_PATH/default/themes/"* ~/.config/omarchy/themes/
try cp "$OMARCHY_PATH/default/themes/catpuccin" ~/.config/omarchy/current/

echo "Migrating themes..."
try mkdir -p ~/.config/btop/themes
# Symlinks - using ln -sf is idempotent
try ln -snf ~/.config/omarchy/current/theme/btop.theme ~/.config/btop/themes/current.theme

try mkdir -p ~/.config/mako
try ln -snf ~/.config/omarchy/current/theme/mako.ini ~/.config/mako/config

# Sudoers
if ! sudo grep -q "passwd_tries=10" /etc/sudoers.d/passwd-tries 2>/dev/null; then
    echo "Setting sudo passwd_tries..."
    echo "Defaults passwd_tries=10" | try sudo tee /etc/sudoers.d/passwd-tries > /dev/null
    try sudo chmod 440 /etc/sudoers.d/passwd-tries
else
    echo "Sudo passwd_tries already set."
fi

echo "Omarchy patch completed!"
